name: Daily Email

on:
  schedule:
    - cron: '* * * * *'

jobs:
  email:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Node LTS versions
        uses: actions/setup-node@v3
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_APP_PASSWORD: ${{ secrets.SENDER_APP_PASSWORD }}
          RECEIVING_EMAIL: ${{ secrets.RECEIVING_EMAIL }}
          
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run dev
