name: Scheduled Email

on:
  workflow_dispatch: {}
  schedule:
#   Runs every second hour.
    - cron: '* */2 * * *'
  
jobs:
  email:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      
      - name: Node LTS versions
        uses: actions/setup-node@v3
          
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install Node.js dependencies
        run: |
          npm i -g pnpm
          pnpm i
        
      - env:
            SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
            SENDER_APP_PASSWORD: ${{ secrets.SENDER_APP_PASSWORD }}
            RECEIVING_EMAIL: ${{ secrets.RECEIVING_EMAIL }}
            NO_OF_HIGHLIGHTS: ${{ secrets.NO_OF_HIGHLIGHTS }}
        run: pnpm run start
